# Generated by Django 4.1.7 on 2023-05-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_gameroom_creator_alter_gameroom_opponent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="source",
        ),
        migrations.RemoveField(
            model_name="edge",
            name="target",
        ),
        migrations.DeleteModel(
            name="GameRoom",
        ),
        migrations.DeleteModel(
            name="Edge",
        ),
        migrations.DeleteModel(
            name="Node",
        ),
    ]
